=== a2g/20210404Travis/schema/XSD.XSD
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2021 rel. 2 sp1 (x64) (http://www.altova.com) -->
<xs:schema vc:minVersion="1.1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
	<xs:element name="json">
		<xs:complexType>
			<xs:all>
				<xs:element minOccurs="1" name="objects">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="2" maxOccurs="unbounded" name="item" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="1" name="transactions">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="1" maxOccurs="unbounded" name="transaction">
								<xs:complexType>
									<xs:all>
										<xs:element minOccurs="1" name="inputA">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="map"/>
													<xs:enumeration value="compass"/>
													<xs:enumeration value="flare"/>
													<xs:enumeration value="flaregun"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element minOccurs="1" name="inputB">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="map"/>
													<xs:enumeration value="compass"/>
													<xs:enumeration value="flare"/>
													<xs:enumeration value="flaregun"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:all>
									<xs:anyAttribute processContents="skip"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
			</xs:all>
			<xs:anyAttribute processContents="skip"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== a2g/20210404Travis/schema/EXAMPLE.XML
<?xml version="1.1" encoding="UTF-8"?>
<json xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/javascript/20210505Typescript/schema/XSD.XSD">
<objects>
	<item></item>
	<item></item>
</objects>
<transactions>
	<transaction>
		<inputA>flare</inputA>
		<inputB>flaregun</inputB>
	</transaction>
</transactions>
</json>
